# TODO write some comments

mysql:
  host: "localhost:3306"
  database-name: "ablockalypse"
  username: "user"
  password: "password"


character:
  nurse:
    display-name: "&aNurse"
    description: "&7Raises effectiveness of bandages/ first aid kits"
    menu:
      index: 10
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  farmer:
    display-name: "&aFarmer"
    description: "&7Can repair armour"
    menu:
      index: 11
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  sprinter:
    display-name: "&aSprinter"
    description: "&7Can sprint faster"
    menu:
      index: 12
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  construction_worker:
    display-name: "&aConstruction Worker"
    description: "&7Reduces damage taken"
    menu:
      index: 13
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  police_officer:
    display-name: "&aPolice Officer"
    description: "&7Does more weapon damage"
    menu:
      index: 14
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  shop_owner:
    display-name: "&aShop Owner"
    description: "&7Items cost less"
    menu:
      index: 15
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  mechanic:
    display-name: "&aMechanic"
    description: "&7Can repair weapons"
    menu:
      index: 16
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  chef:
    display-name: "&aChef"
    description: "&7Raises effectiveness of all foods"
    menu:
      index: 19
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  dog_walker:
    display-name: "&aDog Walker"
    description: "&7Can tame/ starts with wolf (can re-tame wolves if they lose theirs)"
    menu:
      index: 20
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  warehouse_worker:
    display-name: "&aWarehouse Worker (Spy?)"
    description: "&7Has Nightvision"
    menu:
      index: 21
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  thief:
    display-name: "&aThief"
    description: "&7Name is hidden at all times (only visible within 5 block radius)"
    menu:
      index: 22
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  gambler:
    display-name: "&aGambler (Youtuber?)"
    description: "&7Increase of luck on mob drops"
    menu:
      index: 23
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  it_consultant:
    display-name: "&aI.T Consultant"
    description: "&7Quiet (zombies can only hear them if within 5 block radius)"
    menu:
      index: 24
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  free_runner:
    display-name: "&aFree Runner"
    description: "&7No fall damage"
    menu:
      index: 25
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  baller:
    display-name: "&aBaller"
    description: "&7Jump Boost"
    menu:
      index: 30
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  survivalist:
    display-name: "&aSurvivalist"
    description: "&7Hunger and Thirst decreases slower"
    menu:
      index: 32
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="

menu:
  character-selection:
    title: "&cSelect a character"
    size: 45
  past-stories:
    title: "&c{player}'s stories (page {page}/{pageTot})"
    items:
      next-page:
        material: ARROW
        name: "&cNext page"
        lore:
          - "&7Click to open the next page"
      prev-page:
        material: ARROW
        name: "&cPrevious page"
        lore:
          - "&7Click to open the previous page"
      player-info:
        material: PLAYER_HEAD
        name: "&c{player}"
        lore:
          - ""
          - "&7Playtime: {playtime}"
      story-entry:
        lore:
          - ""
          - "&7Start date: {startDate}"
          - "&7End date: {endDate}"
          - "&7Survival time: {survivaltime}"
onboarding:
  cinematic-delay-seconds: 3

format:
  date-time: "yyyy-MM-dd HH:mm:ss"
  duration: "d 'days', mm 'minutes', ss 'seconds'"

message:
  player-only: "&cThis command must be run by a player."
  no-permission: "&cYou don't have permissions"
  config-reloaded: "&cConfig reloaded."
  invalid-character-type: "&c{input} is not a valid character. Valid types: {valid}"
  spawn-add-success: "&aSpawn location set with success"
  spawn-add-already: "&cThis location was already set"
  spawn-tp-invalid: "&cInvalid location"
  spawn-tp-success: "&aTeleporting to the spawnpoint..."
  spawn-list-none: "&cThere isn't any spawn point"
  spawn-list-header: "&aSpawn locations. Click to teleport"
  spawn-list-entry: "&7 - {world} x={x} y={y} z={z}, pitch={pitch}, yaw={yaw}"
  spawn-remove-success: "&aLocation removed with success"
  spawn-remove-none: "&cThis location is not set"
  hospital-add-success: "&aHospital location added with success"
  hospital-add-already: "&cThis hospital location was already set"
  hospital-tp-invalid: "&cInvalid location"
  hospital-tp-success: "&aTeleporting to the hospital..."
  hospital-list-none: "&cThere isn't any hospital spawn point"
  hospital-list-header: "&aHospital spawn locations. Click to teleport"
  hospital-list-entry: "&7 - {world} x={x} y={y} z={z}, pitch={pitch}, yaw={yaw}"
  hospital-remove-success: "&aLocation removed with success"
  hospital-remove-none: "&cThis is not a hospital spawn location"
  cinematic-location-set-success: "&aCinematic location for {character} set with success"
  cinematic-location-tp: "&aTeleporting to the cinematic location for the character {character}..."
  cinematic-location-none: "&cThe cinematic location of the character {character} is not set"
  character-selector-already: "&cYou have already selected a character. You'll be able to change it once you die."
  onboarding-prompt-cancel: "&cType 'CANCEL' to exit."
  onboarding-prompt-cancelled: "&cThe character selection process has been cancelled"
  onboarding-prompt-confirm: "&aAre you sure you want to be a {character}&a? Write yes or no"
  onboarding-prompt-name: "&aWhat's your character's name? &7(8-20 chars long, no special chars)"
  onboarding-prompt-creating: "&eCreating your character..."
  onboarding-prompt-started: "&a{character_name} welcome!"
  stories-target-invalid: "&cUnable to find the player {name}"
  stories-own-none: "&cYou haven't started any story yet"
  stories-other-none: "&cThe player {name} haven't started any story"
  anvil-armor-no: "&cOnly Farmers can repair armor"
  anvil-weapon-no: "&cOnly Mechanics can repair weapons"
  tame-no: "&cYou can't tame this mob"
  tame-wolf-already: "&cYou can tame only 1 wolf!"
  tame-wolf-only-dogwalker: "&cOnly dog walkers can tame wolves!"
  help-menu:
    - "&aAblockalypse commands:"
    - " &c/ablockalypse reload - &7Reload the config"
    - " &c/ablockalypse backstory - &7Open the select character menu"
    - " &c/ablockalypse stories <player> - &7Shows past stories of a player"
    - " &c/ablockalypse hospital list - &7Display all hospital locations"
    - " &c/ablockalypse hospital add - &7Add a hospital location"
    - " &c/ablockalypse hospital remove - &7Remove a hospital location"
    - " &c/ablockalypse cinematic <character> set - &7Set the cinematic room location of a char"
    - " &c/ablockalypse cinematic <character> tp - &7Tp to a cinematic room"
    - " &c/ablockalypse spawnpoint list - &7Display all spawn locations"
    - " &c/ablockalypse spawnpoint add - &7Mark a location as a spawn"
    - " &c/ablockalypse spawnpoint remove - &7Remove a location from the spawn list"
