mysql:
  host: "localhost:3306"
  database-name: "ablockalypse"
  username: "user"
  password: "password"


character:
  nurse:
    display-name: "&aNurse"
    description:
      - "&7Raises effectiveness of bandages/ first aid kits"
    menu:
      index: 10
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      # placeholders:
      # {name} -> player's name
      # {uuid} -> player's uuid
      story-start: [ ]
      story-end: [ ]
      level-increase:
        2: [ ]
        3: [ ]
        4: [ ]
  tailor:
    display-name: "&aTailor"
    description:
      - "&7Can repair armour"
    menu:
      index: 11
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  sprinter:
    display-name: "&aSprinter"
    description:
      - "&7Can sprint faster"
    menu:
      index: 12
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  officer:
    display-name: "&aOfficer"
    description:
      - "&7Reduces damage taken"
    menu:
      index: 13
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  private:
    display-name: "&aPrivate"
    description:
      - "&7Does more weapon damage"
    menu:
      index: 14
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  repair_tech:
    display-name: "&aRepair Tech"
    description:
      - "&7Can repair weapons"
    menu:
      index: 15
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  cook:
    display-name: "&aCook"
    description:
      - "&7Raises effectiveness of all foods"
    menu:
      index: 16
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  veterinarian:
    display-name: "&aVeterinarian"
    description:
      - "&7Can tame/ starts with wolf (can re-tame wolves if they lose theirs)"
    menu:
      index: 19
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  spy:
    display-name: "&aSpy"
    description:
      - "&7Has Nightvision"
    menu:
      index: 20
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  locksmith:
    display-name: "&aLocksmith"
    description:
      - "&7Name is hidden at all times (only visible within 5 block radius)"
    menu:
      index: 21
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  gambler:
    display-name: "&aGambler (Youtuber?)"
    description:
      - "&7Increase of luck on mob drops"
    menu:
      index: 22
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  librarian:
    display-name: "&aLibrarian"
    description:
      - "&7Quiet (zombies can only hear them if within 5 block radius)"
    menu:
      index: 23
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  free_runner:
    display-name: "&aFree Runner"
    description:
      - "&7No fall damage"
    menu:
      index: 24
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  baller:
    display-name: "&aBaller"
    description:
      - "&7Jump Boost"
    menu:
      index: 25
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
  survivalist:
    display-name: "&aSurvivalist"
    description:
      - "&7Hunger and Thirst decreases slower"
    menu:
      index: 31
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
    run-commands:
      story-start: [ ]
      story-end: [ ]
menu:
  character-selection:
    title: "&cSelect a character"
    size: 45
    no-permission:
      - ""
      - "&cYou can't select this character"
  past-stories:
    title: "&c{player}'s stories (page {page}/{pageTot})"
    items:
      next-page:
        material: ARROW
        name: "&cNext page"
        lore:
          - "&7Click to open the next page"
      prev-page:
        material: ARROW
        name: "&cPrevious page"
        lore:
          - "&7Click to open the previous page"
      player-info:
        material: PLAYER_HEAD
        name: "&c{player}"
        lore:
          - ""
          - "&7Playtime: {playtime}"
      story-entry-active:
        lore:
          - ""
          - "&7Start date: {startDate}"
          - "&7Survival time: {survivaltime}"
          - "&7Level: {level}"
      story-entry-past:
        lore:
          - ""
          - "&7Start date: {startDate}"
          - "&7End date: {endDate}"
          - "&7Survival time: {survivaltime}"
          - "&7Level: {level}"
          - "&7Death cause: {deathCause}"
          - "&7Death location: {deathLocation}"
onboarding:
  cinematic-delay-seconds: 3

format:
  date-time: "yyyy-MM-dd HH:mm:ss"
  # duration format docs: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html
  duration: "d 'days', HH 'hours', mm 'minutes'"

leaderboard:
  # How often should the leaderboard be updated?
  refresh-interval-seconds: 300
  # How many stories should be included in the leaderboard?
  max-entries: 10

# The name of the world where all safehouses are
safehouse-world: "world"

safehouse-commands:
  # Commands to run when a player claims a safehouse
  # {name} -> player's name
  claim: [ ]
  # Commands to run when a player loses a safehouse
  loss:
    - "cmi removehome home {name}"

# Specify at what time(s) players can raid safehouses
safehouse-raid-windows:
  # please make sure they don't overlap
  1:
    start: "10:15:00"
    end: "10:45:00"
  2:
    start: "23:15:00"
    end: "23:45:00"
  # you can add as many sections as you need

message:
  player-only: "&cThis command must be run by a player."
  no-permission: "&cYou don't have permissions"
  config-reloaded: "&cConfig reloaded."
  invalid-character-type: "&c{input} is not a valid character. Valid types: {valid}"
  spawn-add-success: "&aSpawn location set with success"
  spawn-add-already: "&cThis location was already set"
  spawn-tp-invalid: "&cInvalid location"
  spawn-tp-success: "&aTeleporting to the spawnpoint..."
  spawn-list-none: "&cThere isn't any spawn point"
  spawn-list-header: "&aSpawn locations. Click to teleport"
  spawn-list-entry: "&7 - {world} x={x} y={y} z={z}, pitch={pitch}, yaw={yaw}"
  spawn-remove-success: "&aLocation removed with success"
  spawn-remove-none: "&cThis location is not set"
  hospital-add-success: "&aHospital location added with success"
  hospital-add-already: "&cThis hospital location was already set"
  hospital-tp-invalid: "&cInvalid location"
  hospital-tp-success: "&aTeleporting to the hospital..."
  hospital-list-none: "&cThere isn't any hospital spawn point"
  hospital-list-header: "&aHospital spawn locations. Click to teleport"
  hospital-list-entry: "&7 - {world} x={x} y={y} z={z}, pitch={pitch}, yaw={yaw}"
  hospital-remove-success: "&aLocation removed with success"
  hospital-remove-none: "&cThis is not a hospital spawn location"
  cinematic-location-set-success: "&aCinematic location for {character} set with success"
  cinematic-location-tp: "&aTeleporting to the cinematic location for the character {character}..."
  cinematic-location-none: "&cThe cinematic location of the character {character} is not set"
  character-selector-already: "&cYou have already selected a character. You'll be able to change it once you die."
  character-selector-no-permission: "&cYou don't have the permission to select this character."
  onboarding-prompt-cancelled: "&cThe character selection process has been cancelled"
  onboarding-prompt-confirm: "&aAre you sure you want to be a {character}&a? Write yes or no"
  onboarding-prompt-name: "&aWhat's your character's name? &7(3-20 chars long, no special chars)"
  onboarding-prompt-creating: "&eCreating your character..."
  onboarding-prompt-started: "&a{character_name} welcome!"
  stories-target-invalid: "&cUnable to find the player {name}"
  stories-own-none: "&cYou haven't started any story yet"
  stories-other-none: "&cThe player {name} haven't started any story"
  anvil-armor-no: "&cOnly Tailors can repair armor"
  anvil-weapon-no: "&cOnly Repair Techs can repair weapons"
  tame-no: "&cYou can't tame this mob"
  tame-wolf-already: "&cYou can tame only 1 wolf!"
  tame-wolf-only-dogwalker: "&cOnly dog walkers can tame wolves!"
  safehouse-create-success: "&aYou have create a new safehouse! Its id is {id}. You can use it in commands to reference it"
  safehouse-create-invalid-region: "&cUnable to find the region {name} in this world"
  safehouse-create-invalid-exists: "&cThere is already a safehouse at the region {name}"
  safehouse-cmd-invalid-id: "&cUnable to find a safehouse identified by {id-region}"
  safehouse-spawn-not-set: "&cThe safehouse location is not configured. Please set it first"
  safehouse-spawn-teleporting: "&aTeleporting to the safehouse spawn..."
  safehouse-spawn-set-invalid: "&cThe safehouse spawn must be inside the house"
  safehouse-spawn-set: "&aSafehouse spawn set with success"
  safehouse-outside-set-invalid: "&cThe safehouse outside location can't be inside the house"
  safehouse-outside-set: "&aSafehouse outside location set"
  safehouse-door-set-invalid: "&cThe safehouse door must be a door"
  safehouse-door-set-invalid-half: "&cPlease point to the top half of the door"
  safehouse-door-set: "&aSafehouse door set with success"
  safehouse-door-level-increased: "&aYou increased the door level to {level}"
  safehouse-upgrade-door-success: "&aYou upgraded the door to level {level}"
  safehouse-upgrade-door-failure: "&cYou don't have enough resources to upgrade the door"
  safehouse-upgrade-door-level-2-first: "&cYou must upgrade the door to level 2 before upgrading it to level 3"
  safehouse-deleted: "&aSafehouse deleted"
  safehouse-deleted-owner: "&cYour safehouse was deleted"
  safehouse-block-place: "&cOnly the owner is allowed to place blocks in the safehouse!"
  safehouse-block-break: "&cOnly the owner is allowed to break blocks in the safehouse!"
  safehouse-block-break-blocked: "&cYou can't break this safehouse block!"
  safehouse-click-claimed: "&cThis is a claimed safehouse. Use a crowbar or lockpick to raid it."
  safehouse-click-not-claimed: "&cThis is an unclaimed safehouse. Use a key to claim it for your own!"
  safehouse-setowner-already: "&cThe house already has an owner"
  safehouse-setowner-not-found: "&cUnable to find the target player"
  safehouse-setowner-set: "&aSafehouse owner set!"
  safehouse-settype-invalid: "&cInvalid safehouse type"
  safehouse-settype-set: "&aSafehouse type set"
  safehouse-booster-activated: "&aYou activated the safehouse {booster} booster"
  safehouse-booster-deactivated: "&cYou deactivated the safehouse {booster} booster"
  safehouse-booster-max: "&cYou can't activate more than {max} boosters"
  safehouse-not-owner: "&cYou don't own a safehouse"
  safehouse-claimedlist-empty: "&cThere isn't any claimed claimed safehouse"
  safehouse-claimedlist-entry: "&7{idx} {region} - {owner_name}"
  compass-searching: "&aSearching for the nearest unclaimed safehouse..."
  compass-found: "&aCompass pointing to the nearest safehouse!"
  compass-none: "&cThere isn't any unclaimed safehouse"
  claim-recent-no: "&cThe house was raided less than 10 minutes ago. During this time, only the previous owner and the player who broke in are allowed to claim it"
  claim-already-own: "&cYou already own a safehouse. If you claim this one, you will lose your house and its content"
  claim-already-owned: "&cThis house is owned by another player. You need to break in before claiming it!"
  claim-not-sneaking: "&cYou need to sneak and right click to claim the house!"
  claim-started: "&aRight click for {seconds} more seconds to claim the safehouse!"
  claim-during: "&aHold for {seconds} more seconds..."
  claim-started-owner: "&cSomeone is trying claim your previous safehouse!"
  claim-done-previous-owner: "&cYou lost your house, someone managed to claim it!"
  claim-done: "&aYou claimed the house! You are the new owner!"
  claim-done-lost: "&aSince you decided to claim this house, you lost your other house."
  break-in-not-needed: "&aYou can claim the house with a key, there's no need to break in!"
  break-in-bunker-no: "&cYou can't break into bunkers"
  break-in-disallow: "&cYou can't break in! You can break in only at specific day times or when owner is online"
  break-in-not-sneaking: "&cYou need to sneak and right click to break in!"
  break-in-started: "&aRight click for {seconds} more seconds to break in!"
  break-in-during: "&aHold for {seconds} more seconds..."
  break-in-started-owner: "&c{character-name} is raiding your house!"
  break-in-done-owner: "&cSomeone broke into your house! You have 10 minutes to re-claim it!"
  break-in-done: "&aYou broke into the house! During the next 10 minutes, you and the previous owner will be the only ones able to claim it!"
  help-menu:
    - "&aAblockalypse commands:"
    - " &c/ablockalypse reload - &7Reload the config"
    - " &c/ablockalypse backstory - &7Open the select character menu"
    - " &c/ablockalypse stories <player> - &7Shows past stories of a player"
    - " &c/ablockalypse hospital list - &7Display all hospital locations"
    - " &c/ablockalypse hospital add - &7Add a hospital location"
    - " &c/ablockalypse hospital remove - &7Remove a hospital location"
    - " &c/ablockalypse cinematic <character> set - &7Set the cinematic room location of a char"
    - " &c/ablockalypse cinematic <character> tp - &7Tp to a cinematic room"
    - " &c/ablockalypse spawnpoint list - &7Display all spawn locations"
    - " &c/ablockalypse spawnpoint add - &7Mark a location as a spawn"
    - " &c/ablockalypse spawnpoint remove - &7Remove a location from the spawn list"
    - " &c/ablockalypse story <player> nextlevel - &7Increase the level of the player's active story"
    - " &c/ablockalypse reset <player/all> current - &7Reset back to the start of their current run"
    - " &c/ablockalypse reset <player/all> history - &7Reset all stories, including the active one"
    - " &c/ablockalypse safehouse <region> create  - &7Create a new safehouse at the specified worldguard region"
    - " &c/ablockalypse safehouse <region|id> delete - &7Delete a safehouse"
    - " &c/ablockalypse safehouse <region|id> teleport - &7Teleport to the house spawn"
    - " &c/ablockalypse safehouse <region|id> setdoor - &7Set the pointed door as the safehouse door"
    - " &c/ablockalypse safehouse <region|id> setspawn - &7Set the pointed door as the safehouse door"
    - " &c/ablockalypse safehouse <region|id> setoutside - &7Set the safehouse outside location"
    - " &c/ablockalypse safehouse <region|id> nextdoorlevel - &7Increases the door level"
    - " &c/ablockalypse safehouse <region|id> setowner <player> - &7Sets the owner of a safehouse"
    - " &c/ablockalypse safehouse <region|id> settype <type> - &7Sets the type of a safehouse"
    - " &c/ablockalypse safehouse boosters - &7Opens the boosters menu"
    - " &c/ablockalypse safehouse door - &7Opens the door upgrade menu"
    - " &c/ablockalypse safehouse teleport - &7Teleport to owned safehouse"
    - " &c/ablockalypse safehouse claimedlist - &7Display all claimed safehouses"
