# TODO write some comments

mysql:
  host: "localhost:3306"
  database-name: "ablockalypse"
  username: "user"
  password: "password"


character:
  nurse:
    display-name: "&aNurse"
    description: "Raises effectiveness of bandages/ first aid kits"
    menu:
      index: 0
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  farmer:
    display-name: "&aFarmer"
    description: "Can repair armour"
    menu:
      index: 1
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  sprinter:
    display-name: "&aSprinter"
    description: "Can sprint faster"
    menu:
      index: 2
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  construction_worker:
    display-name: "&aConstruction Worker"
    description: "Reduces damage taken"
    menu:
      index: 3
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  police_officer:
    display-name: "&aPolice Officer"
    description: "Does more weapon damage"
    menu:
      index: 4
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  shop_owner:
    display-name: "&aShop Owner"
    description: "Items cost less"
    menu:
      index: 5
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  mechanic:
    display-name: "&aMechanic"
    description: "Can repair weapons"
    menu:
      index: 6
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  chef:
    display-name: "&aChef"
    description: "Raises effectiveness of all foods"
    menu:
      index: 7
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  dog_walker:
    display-name: "&aDog Walker"
    description: "Can tame/ starts with wolf (can re-tame wolves if they lose theirs)"
    menu:
      index: 8
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  warehouse_worker:
    display-name: "&aWarehouse Worker (Spy?)"
    description: "Has Nightvision"
    menu:
      index: 9
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  thief:
    display-name: "&aThief"
    description: "Name is hidden at all times (only visible within 5 block radius)"
    menu:
      index: 10
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  gambler:
    display-name: "&aGambler (Youtuber?)"
    description: "Increase of luck on mob drops"
    menu:
      index: 11
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  it_consultant:
    display-name: "&aI.T Consultant"
    description: "Quiet (zombies can only hear them if within 5 block radius)"
    menu:
      index: 12
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  free_runner:
    display-name: "&aFree Runner"
    description: "No fall damage"
    menu:
      index: 13
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  baller:
    display-name: "&aBaller"
    description: "Jump Boost"
    menu:
      index: 14
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="
  survivalist:
    display-name: "&aSurvivalist"
    description: "Hunger and Thirst decreases slower"
    menu:
      index: 15
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIyNDZjOGFiZTdmMzczMmNlZjc1ODM3OTM1M2EyODgxNWE5YzM3MDdiMzIxMjk1NzMxZTIyMTVhYmFmNmZhZiJ9fX0="

menu:
  character-selection:
    title: "&cSelect a character"
    size: 36

onboarding:
  cinematic-delay-seconds: 5

message:
  player-only: "&cThis command must be run by a player."
  invalid-character-type: "&c{input} is not a valid character. Valid types: {valid}"
  hospital-location-set: "&aHospital location set with success"
  hospital-location-tp: "&aTeleporting to the hospital..."
  hospital-location-none: "&cThe hospital location is not set"
  spawn-add-success: "&aLocation set with success"
  spawn-add-already: "&cThis location was already set"
  spawn-list-none: "&cThere isn't any spawn point"
  spawn-list-header: "&aSpawn locations. Click to teleport"
  spawn-list-entry: "&7{world} {x} {y} {z}, pitch={pitch}, yaw={yaw}"
  spawn-remove-success: "&aLocation removed with success"
  spawn-remove-none: "&cThis location is not set"
  cinematic-location-set-success: "&aCinematic location for {character} set with success"
  cinematic-location-tp: "&aTeleporting to the cinematic location for the character {character}..."
  cinematic-location-none: "&cThe cinematic location of the character {character} is not set"
  character-selector-already: "&cYou have already selected a character. You'll be able to change it once you die."