mysql:
  host: 'localhost:3306'
  database-name: 'ablockalypse'
  username: 'user'
  password: 'password'


character:
  nurse:
    display-name: "&aNurse"
    description: "Raises effectiveness of bandages/ first aid kits"
    menu:
      index: 10
      texture: aa #TODO set
  farmer:
    display-name: "&aFarmer"
    description: "Can repair armour"
  sprinter:
    display-name: "&aSprinter"
    description: "Can sprint faster"
  construction_worker:
    display-name: "&aConstruction Worker"
    description: "Reduces damage taken"
  police_officer:
    display-name: "&aPolice Officer"
    description: "Does more weapon damage"
  shop_owner:
    display-name: "&aShop Owner"
    description: "Items cost less"
  mechanic:
    display-name: "&aMechanic"
    description: "Can repair weapons"
  chef:
    display-name: "&aChef"
    description: "Raises effectiveness of all foods"
  dog_walker:
    display-name: "&aDog Walker"
    description: "Can tame/ starts with wolf (can re-tame wolves if they lose theirs)"
  warehouse_worker:
    display-name: "&aWarehouse Worker (Spy?)"
    description: "Has Nightvision"
  thief:
    display-name: "&aThief"
    description: "Name is hidden at all times (only visible within 5 block radius)"
  gambler:
    display-name: "&aGambler (Youtuber?)"
    description: "Increase of luck on mob drops"
  it_consultant:
    display-name: "&aI.T Consultant"
    description: "Quiet (zombies can only hear them if within 5 block radius)"
  free_runner:
    display-name: "&aFree Runner"
    description: "No fall damage"
  baller:
    display-name: "&aBaller"
    description: "Jump Boost"
  survivalist:
    display-name: "&aSurvivalist"
    description: "Hunger and Thirst decreases slower"

menu:
  character-selection:
    title: "&cSelect a character"
    size: 36

message:
  player-only: "&cThis command must be run by a player."
  invalid-character-type: "&c{input} is not a valid character. Valid types: {valid}"
  hospital-location-set: "&aHospital location set with success"
  hospital-location-tp: "&aTeleporting to the hospital..."
  hospital-location-none: "&cThe hospital location is not set"
  spawn-add-success: "&aLocation set with success"
  spawn-add-already: "&cThis location was already set"
  spawn-list-none: "&cThere isn't any spawn point"
  spawn-list-header: "&aSpawn locations. Click to teleport"
  spawn-list-entry: "&7{world} {x} {y} {z}, pitch={pitch}, yaw={yaw}"
  spawn-remove-success: "&aLocation removed with success"
  spawn-remove-none: "&cThis location is not set"
  cinematic-location-set-success: "&aCinematic location for {character} set with success"
  cinematic-location-tp: "&aTeleporting to the cinematic location for the character {character}..."
  cinematic-location-none: "&cThe cinematic location of the character {character} is not set"
  character-selector-already: "&cYou have already selected a character. You'll be able to change it once you die."