name: Ablockalypse
version: ${version}
main: com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin
api-version: 1.18
authors: [ GamerSafer ]
softdepend: [ PlaceholderAPI, ProtocolLib ]
depend: [ WorldGuard, Parties, MMOItems, HeadDatabase ]

commands:
  ablockalypse:
    description: Main command
    aliases: [ "ablock" ]
  stories:
    description: Main command
  backstory:
    description: Main command
  safehouse:
    description: Main command
