name: Ablockalypse
version: ${version}
main: com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin
api-version: 1.18
authors: [ GamerSafer ]
softdepend: [ PlaceholderAPI ]

commands:
  ablockalypse:
    description: Main command