name: Ablockalypse
version: ${version}
main: com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin
api-version: 1.18
authors: [ GamerSafer ]
softdepend: [ PlaceholderAPI, ProtocolLib, TagAPI ] # FIXME remove TagAPI once shaded

commands:
  ablockalypse:
    description: Main command